# Generated by Django 4.0.4 on 2022-05-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stripe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD')], default='rub', max_length=15, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_discount', to='Stripe.item', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
