# Generated by Django 4.0.4 on 2022-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stripe', '0009_order_delete_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='item_order', to='Stripe.item', verbose_name='Товар'),
        ),
    ]
