# Generated by Django 4.0.4 on 2022-05-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stripe', '0012_remove_item_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая стоимость'),
        ),
    ]
